### ISSUE TITLE
Modify 'game started' embed once betting closes

### ISSUE THREAD

**Issue by bigfoott** [zainaraza43/the-house#2]
When you can no longer place bets on a match, modify the embed to:
- Remove the 'bet' button
- List the bets on this match

**Comment by zainaraza43** [comment]
I think these solutions are kind of intensive. 

- Removing the Bet button would make each message wait would be a process in itself
- Listing current bets could possibly promote match fixing so I'll avoid this for now

I think it should just say that the bet expired or something in reply.

**Comment by bigfoott** [comment]
The point on match-fixing makes sense. Regarding removing the bet button, i think it should be doable if you just edit the message and send the same embed and don't add the button component. Not sure how it would work with the library you're using, but saving the message ID and then sending the edit api call after the fact should work.
