### ISSUE TITLE
Custom bet amounts and betting twice

### ISSUE THREAD

**Issue by abner-garcia-II** [zainaraza43/the-house#9]
Add ability to bet custom amount of aura.
When betting one a game twice for the same outcome, bets are displayed as separate instead of combined. (e.g. Betting 100 on Win and Betting 50 on Win are displayed as Bet 100: Outcome here, Bet 50: Outcome here instead of Bet 150: Outcome here)

**Comment by zainaraza43** [comment]
split this into two
